trigger:
  branches:
    include:
      - main

variables:
  workingDirectory: environments/dev
stages:
- stage: Validate
  displayName: "Terraform Validate"

  jobs:
  - job: Validate
    displayName: "Validate Terraform"

    pool:
      vmImage: ubuntu-latest

    steps:
    - checkout: self

    - script: |
        wget https://releases.hashicorp.com/terraform/1.13.0/terraform_1.13.0_linux_amd64.zip
        unzip terraform_1.13.0_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
        terraform --version
      displayName: Install Terraform

    - script: terraform --version
      displayName: Terraform Version

    - script: |
        cd $(workingDirectory)
        terraform init
      displayName: Terraform Init

    - script: |
        cd $(workingDirectory)
        terraform validate
      displayName: Terraform Validate

    